# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IdeGen < Formula
  desc ""
  homepage "https://github.com/vladarts/ide-gen"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vladarts/ide-gen/releases/download/v0.0.6/ide-gen_Darwin_x86_64.tar.gz"
      sha256 "cb530b499818d2e8a575c32a202f0bae5ab1aa6a4ffd588ca96cfc8c32a02921"

      def install
        bin.install "ide-gen"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "bash")
        (bash_completion/"ide-gen").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "zsh")
        (zsh_completion/"_ide-gen").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vladarts/ide-gen/releases/download/v0.0.6/ide-gen_Darwin_arm64.tar.gz"
      sha256 "19445cfae01e7788a82779ed069947da18376168f156a2b30760b4b8d935bba9"

      def install
        bin.install "ide-gen"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "bash")
        (bash_completion/"ide-gen").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "zsh")
        (zsh_completion/"_ide-gen").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/vladarts/ide-gen/releases/download/v0.0.6/ide-gen_Linux_x86_64.tar.gz"
      sha256 "620de4502e9b71d49c00f47556b4bb5ca6a1175c4f869babc3d11c4745233c83"
      def install
        bin.install "ide-gen"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "bash")
        (bash_completion/"ide-gen").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "zsh")
        (zsh_completion/"_ide-gen").write output
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/vladarts/ide-gen/releases/download/v0.0.6/ide-gen_Linux_arm64.tar.gz"
      sha256 "62cab3b41145abc426623d28af26683d49cb6a2e466e36db52ff4fef16d0538f"
      def install
        bin.install "ide-gen"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "bash")
        (bash_completion/"ide-gen").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "zsh")
        (zsh_completion/"_ide-gen").write output
      end
    end
  end

  test do
    system "#{bin}/ide-gen version"
  end
end
