# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IdeGen < Formula
  desc ""
  homepage "https://github.com/xxxbobrxxx/ide-gen"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/xxxbobrxxx/ide-gen/releases/download/v0.0.2/ide-gen_0.0.2_Darwin_arm64.tar.gz"
      sha256 "687b1a96ccaf999c9306bc807b44be526c66826eb0e0f6b1a7ed58358ad1a6de"

      def install
        bin.install "ide-gen"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "bash")
        (bash_completion/"ide-gen").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "zsh")
        (zsh_completion/"_ide-gen").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/xxxbobrxxx/ide-gen/releases/download/v0.0.2/ide-gen_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "6dda54698a0224063d41baff1db0a22181deee19d8595294cffd052e2474e92f"

      def install
        bin.install "ide-gen"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "bash")
        (bash_completion/"ide-gen").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "zsh")
        (zsh_completion/"_ide-gen").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xxxbobrxxx/ide-gen/releases/download/v0.0.2/ide-gen_0.0.2_Linux_arm64.tar.gz"
      sha256 "7b971d6ad3c8bf40d207462399a15613fd86bccb2a360cabf54932d452f233d7"

      def install
        bin.install "ide-gen"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "bash")
        (bash_completion/"ide-gen").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "zsh")
        (zsh_completion/"_ide-gen").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/xxxbobrxxx/ide-gen/releases/download/v0.0.2/ide-gen_0.0.2_Linux_x86_64.tar.gz"
      sha256 "f4393195c483aa7b426226dd93a119d95243923ba7a0f39ec790edf87235bdbd"

      def install
        bin.install "ide-gen"

        # Install bash completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "bash")
        (bash_completion/"ide-gen").write output

        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "zsh")
        (zsh_completion/"_ide-gen").write output
      end
    end
  end

  test do
    system "#{bin}/ide-gen version"
  end
end
