# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IdeGen < Formula
  desc ""
  homepage "https://github.com/vladarts/ide-gen"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vladarts/ide-gen/releases/download/v0.0.5/ide-gen_Darwin_arm64.tar.gz"
      sha256 "337499258a908e9ecce5affe5a3a95bfc8fa86b157705f3b43ca92b755ef1707"

      def install
        bin.install "ide-gen"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "bash")
        (bash_completion/"ide-gen").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "zsh")
        (zsh_completion/"_ide-gen").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vladarts/ide-gen/releases/download/v0.0.5/ide-gen_Darwin_x86_64.tar.gz"
      sha256 "03208c5e45c2889160c5b8938eff52e6c727cdd537a15c5a1191056bbff4020f"

      def install
        bin.install "ide-gen"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "bash")
        (bash_completion/"ide-gen").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "zsh")
        (zsh_completion/"_ide-gen").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vladarts/ide-gen/releases/download/v0.0.5/ide-gen_Linux_arm64.tar.gz"
      sha256 "904184c9caf8d9a29d9a0adc19901be1e0cafbb3c774226ae46ce33e237bd847"

      def install
        bin.install "ide-gen"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "bash")
        (bash_completion/"ide-gen").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "zsh")
        (zsh_completion/"_ide-gen").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vladarts/ide-gen/releases/download/v0.0.5/ide-gen_Linux_x86_64.tar.gz"
      sha256 "7f82108d67dfdd1b7ea249c48283ac743995626c8748b326f7939469df8376b8"

      def install
        bin.install "ide-gen"
        # Install bash completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "bash")
        (bash_completion/"ide-gen").write output
        # Install zsh completion
        output = Utils.safe_popen_read(bin/"ide-gen", "completion", "zsh")
        (zsh_completion/"_ide-gen").write output
      end
    end
  end

  test do
    system "#{bin}/ide-gen version"
  end
end
